name: Build

on: push

jobs:
    build:
        strategy:
            matrix:
                directory: [backend, frontend]
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{ matrix.directory }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build
